# Generated by Django 4.0.3 on 2022-03-05 17:57

import company.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=500)),
                ('CIK_Number', models.CharField(default='', max_length=50)),
                ('Ticket_Number', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Growth', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Profitability', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Investibility', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('CompanyS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metric_Type', models.CharField(choices=[('Type1', 'GrowthRate'), ('Type2', 'CAC')], default='Type1', max_length=5)),
                ('Value', models.FloatField(default=0.0)),
                ('Source_Link', models.URLField()),
                ('Year', models.IntegerField(default=company.models.current_year, validators=[django.core.validators.MinValueValidator(2015), company.models.max_value_current_year], verbose_name='year')),
                ('Quarter', models.CharField(choices=[('1', '1st quarter'), ('2', '2nd quarter'), ('3', '3rd quarter'), ('4', '4th quarter')], default=1, max_length=1)),
                ('CompanyS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDGAR_Link', models.URLField()),
                ('Form_Type', models.CharField(choices=[('Type1', '10k'), ('Type2', '10q'), ('Type3', '8k')], default='Type1', max_length=5)),
                ('CompanyS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
            ],
        ),
    ]
