# Generated by Django 4.0.3 on 2022-03-18 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompFav',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='companys',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companys',
            name='CIK_Number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='Form_Type',
            field=models.CharField(choices=[('10k', '10k'), ('10q', '10q'), ('8k', '8k')], default='10k', max_length=3),
        ),
        migrations.AlterField(
            model_name='forms',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='metrics',
            constraint=models.UniqueConstraint(fields=('Metric_Type', 'Source_Link', 'Year', 'Quarter', 'CompanyS'), name='unique_value'),
        ),
        migrations.AddField(
            model_name='compfav',
            name='CompanyS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
        ),
        migrations.AddField(
            model_name='compfav',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='compfav',
            unique_together={('CompanyS', 'account')},
        ),
    ]
