# Generated by Django 4.0.3 on 2022-03-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_compfav_companys_count_alter_companys_cik_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companys',
            old_name='CIK_Number',
            new_name='cik',
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='Ticket_Number',
            new_name='ticket',
        ),
    ]
