# Generated by Django 4.0.3 on 2022-03-19 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_metrics_quarter_remove_metrics_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='Form_Type',
            field=models.CharField(choices=[('10k', ' 10k'), ('10q', '10q'), ('8k', '8k')], default='10k', max_length=3),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Filing_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Filing_Type',
            field=models.CharField(choices=[('10k', ' 10k'), ('10q', '10q'), ('8k', '8k')], default='10k', max_length=3),
        ),
    ]
