# Generated by Django 4.0.3 on 2022-03-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_cik_number_companys_cik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companys',
            old_name='cik',
            new_name='CIK_Number',
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='ticket',
            new_name='Ticket_Number',
        ),
    ]
